services:
  # service name also used in httpd.conf ServerName field
  httpd1:
    image: 'httpd:2.4.62'
    container_name: httpd1
    volumes:
      - ./httpd1/httpd1.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd1/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      httpd_cluster:
        ipv4_address: 172.10.0.2
  httpd2:
    image: 'httpd:2.4.62'
    container_name: httpd2
    volumes:
      - ./httpd2/httpd2.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd2/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      httpd_cluster:
        ipv4_address: 172.10.0.3
  haproxy:
    image: 'haproxy:2.4.22'
    container_name: haproxy
    ports:
      - '8088:8088'
      - '8081:8081'
      - '8443:8443'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./combined.pem:/etc/haproxy/ssl/combined.pem
    networks:
      httpd_cluster:
        ipv4_address: 172.10.0.4
  haproxy2:
    image: 'haproxy:2.4.22'
    container_name: haproxy2
    ports:
      - '8089:8088'
      - '8082:8081'
      - '8444:8443'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./combined.pem:/etc/haproxy/ssl/combined.pem
    networks:
      httpd_cluster:
        ipv4_address: 172.10.0.5
networks:
  httpd_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
